# .github/workflows/chromatic.yml

name: "Chromatic"

on:
  push:
  pull_request:
    branches: [production]
    types: [opened, synchronize, closed]

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          workingDir: packages/storybook
          # ⚠️ Make sure to configure a `CHROMATIC_PROJECT_TOKEN` repository secret
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
